before_deploy:
  - tnpm install && tnpm update
  - tnpm run just-deploy
options:
  branch: 'master'
  dist: '_site'
thumb: 'https://t.alipayobjects.com/images/rmsweb/T1gqXjXdRfXXXXXXXX.png'
cname: 'antd.alipay.net'
