sudo: false

language: node_js

node_js:
  - "6"

env:
  matrix:
    - TEST_TYPE=lint
    - TEST_TYPE=dist
    - TEST_TYPE=compile
    - TEST_TYPE=test:dom
    - TEST_TYPE=test:node

script:
  - |
    if [ "$TEST_TYPE" = lint ]; then
      npm run lint
    elif [ "$TEST_TYPE" = dist ]; then
      npm run dist && \
      node ./tests/dekko/dist.test.js && \
      LIB_DIR=dist npm test -- --coverage -w 2
    elif [ "$TEST_TYPE" = compile ]; then
      npm run dist && \
      npm run compile && \
      node ./tests/dekko/lib.test.js && \
      LIB_DIR=es npm test -- --coverage -w 2 && \
      LIB_DIR=lib npm test -- --coverage -w 2
    elif [ "$TEST_TYPE" = test:dom ]; then
      npm run dist && \
      npm test -- --coverage -w 2 && \
      bash <(curl -s https://codecov.io/bash)
    elif [ "$TEST_TYPE" = test:node ]; then
      npm run test-node -- -w 2
    fi
