[build]
  publish = "_site"
  command = "npm run site"

[context.production]
  command = "echo build"
  publish = "."

[[redirects]]
  from = "/docs/resource/download"
  to = "/docs/spec/download"
  status = 301
  force = false
