name: Issue Close Require

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issues-helper@v1.2
        with:
          actions: 'close-issues'
          token: ${{ secrets.ANT_BOT_TOKEN }}
          labels: '🤔 Need Reproduce'
          inactive-day: 3
