name: 🔀 Mirror to Gitee

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'ant-design/ant-design'
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:ant-design/ant-design.git'
          destination-repo: 'git@gitee.com:ant-design/ant-design.git'
