# 当 PR 被合并时，留言欢迎加入共建群
name: PullRequest Contributor Welcome

on:
  pull_request_target:
    types:
      - closed
    paths:
      - 'components/**'

jobs:
  check-merged:
    runs-on: ubuntu-latest
    needs: read-file
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🎉 Thanks for contribution. Please feel free to join DingTalk Social Community (Provide the PR link please).

            🎉 感谢参与贡献，欢迎扫码加入钉钉社区（进群后请提供 PR 地址）。

            <img src="https://github.com/ant-design/ant-design/assets/5378891/e24c6080-bf38-4523-b1cd-f6c43ad7375f" height="200" />

            <!-- WELCOME_CONTRIBUTION -->
          body-include: '<!-- WELCOME_CONTRIBUTION -->'