name: PR Labeled

on:
  pull_request_target:
    types: [labeled]

jobs:
  pr-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == 'PR: Need fill changelog'
        uses: actions-cool/issues-helper@v2.1.2
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.number }}
          body: |
            Hi @${{ github.event.pull_request.user.login }}. Please fill in the changelog in the PR. Write with a **developer-oriented perspective** and **narrative method**, without describing the details of the repair, **describing the problem and the impact on the developer**; **describing the user-first site problem**, not your solution.

            你好 @${{ github.event.pull_request.user.login }}。请填写 PR 中的 changelog。请用**面向开发者的角度**和**叙述方式撰写**，不描述修复细节，**描述问题和对开发者的影响**；**描述用户第一现场的问题**，而非你的解决方式。
