name: PR Open Check

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  refuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/pr-welcome@v1.1.2
        with:
          refuse-issue-label: '🎱 Collaborate PR only'
          need-creator-authority: 'write'
          comment: |
            Hi @${{ github.event.pull_request.user.login }}. The issue mentioned in this PR needs to be confirmed with the designer or core team. This PR is temporarily not accepted. Thank you again for your contribution! 😊

            你好 @${{ github.event.pull_request.user.login }}。这个 PR 提及的 issue 需要和设计师或核心团队进行确认，暂时不接受 PR，再次感谢你的贡献！😊   
          pr-emoji: 'heart'
          close: true
