name: Pull Request Stats

on:
  pull_request:
    types: [opened]

jobs:
  stats:
    if: github.repository == 'ant-design/ant-design'
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
