name: Publish to github-package
on:
  release:
    types: [published]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: install
        run: npm install

      - name: compile
        run: npm run compile

      - name: dist
        run: npm run dist

      - uses: actions/upload-artifact@master
        with:
          name: esm
          path: es

      - uses: actions/upload-artifact@master
        with:
          name: cjs
          path: lib

      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

      - uses: actions/upload-artifact@master
        with:
          name: package
          path: package.json

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@master
        with:
          name: esm

      - uses: actions/download-artifact@master
        with:
          name: cjs

      - uses: actions/download-artifact@master
        with:
          name: dist

      - uses: actions/download-artifact@master
        with:
          name: package

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
