name: 📦 Size Limit

on:
  pull_request:
    types: [opened, synchronize]

# Cancel prev CI if new commit come
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  size:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: cache package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: create package-lock.json
        run: npm i --package-lock-only --ignore-scripts

      - name: hack for single file
        run: |
          if [ ! -d "package-temp-dir" ]; then
            mkdir package-temp-dir
          fi
          cp package-lock.json package-temp-dir

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

      - name: size-limit
        uses: ant-design/size-limit-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: dist
          skip_step: install
        env:
          NODE_OPTIONS: --max_old_space_size=4096
